openapi: "3.0.0"
info:
  version: 0.1.0
  title: 포폴 API docs
  description: 포폴의 API 문서입니다
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /api/auth:
    $ref: "./auth.yaml#/"
  /api/auth/login:
    $ref: "./auth.yaml#/login"
  /api/auth/login/naver:
    $ref: "./auth.yaml#/login/naver"
  /api/auth/login/signup:
    $ref: "./auth.yaml#/login/signup"
  /api/auth/logout:
    $ref: "./auth.yaml#/logout"
  /api/user/mypage:
    $ref: "./user.yaml#/mypage"
  /api/user:
    $ref: "./user.yaml#/"
  /api/user{email}:
    $ref: "./user.yaml#/{email}"
  /api/user/{userId}/profile:
    $ref: "./user.yaml#/{userId}/profile"
components:
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
            properties:
